version: '3.4'
services:
  zalenium:
    image: dosel/zalenium
    container_name: zalenium
    hostname: zalenium
    tty: true
    ports:
      - '4444:4444'
    command: |
      start --desiredContainers 2
            --maxDockerSeleniumContainers 2
            --screenWidth 1440 --screenHeight 900
            --timeZone "America/Bogota"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --cbtEnabled false
            --lambdaTestEnabled false
            --startTunnel false
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
      - CBT_USERNAME
      - CBT_AUTHKEY
      - LT_USERNAME
      - LT_ACCESS_KEY
    volumes:
      - '/tmp/videos:/home/seluser/videos'
      - '/var/run/docker.sock:/var/run/docker.sock'
  mock:
    image: elgalu/selenium
    container_name: elgalu_selenium
    depends_on:
      - zalenium
    ports:
      - '8080:8080'
    tty: true
    environment:
      - MOCK_SERVER_PORT=8080
  
  
